### ISSUE TITLE
Please remove dymola.egg from the repo

### ISSUE THREAD

**Issue by t-sommer** [moe93/Pymola#3]
Hi, it's @t-sommer from https://github.com/CATIA-Systems :wave:

We just discovered that you've added the `dymola.egg` from the Dymola installation to your repository.
This file is subject the Dymola license agreement and may not be distributed, so we kindly ask you to remove it
from your repository.

We're also planning a new Python interface for Dymola with the name "Pymola" which we have already reserved
on PyPI, so you might want to consider renaming your project to avoid confusion.

**Comment by moe93** [comment]
Thank you for bringing this to my attention. I had thought I had placed it in the .gitignore file, apparently it slipped through the cracks.

I apologize for that mistake. I will make sure it is removed promptly as soon as I have access to a computer.

Regards,

**Comment by moe93** [comment]
Hello once again @t-sommer.

I have made sure that the .egg file is in the .gitignore list in addition to removing the .egg file from the repository.
As a token of good faith, I have also deleted the entire commit history of this repository to ensure no one can access the .egg file using the commit history.

Regards,
